APP_NAME: boilerplate-service
API:
  LISTEN_ADDR: :8081
  DEBUG_MODE: false
DB_ENABLED: false
DB:
  HOST: localhost
  PORT: 5432
  USER: postgres
  PASSWORD: ""
  NAME: boilerplate
  CONNECT_TIMEOUT: 5s
  MAX_OPEN_CONNS: 5
  MAX_IDLE_CONNS: 1
  CONN_MAX_LIFETIME: 5m0s
  CONN_MAX_IDLE_TIME: 1m0s
LOG_LEVEL: info
LOG_OUTPUT: console
LOG_FORMAT: text
SERVICE_TIMEOUT:
  SAMPLE_SERVICE: 5s
SWAGGER:
  ENABLED: false
  PATH: ""
SAMPLE:
  HOST: ""
